### ISSUE TITLE
scattergun doesn't get fully replenished on kill

### ISSUE THREAD

**Issue by maxijabase** [sapphonie/MGEMod#1] opened 2020-11-27 18:28 UTC
![mgescoutbrokenammo](https://user-images.githubusercontent.com/20617661/100476751-2c9b5500-30c5-11eb-9f33-74976460a0a1.gif)

**Comment by sapphonie** [comment] 2020-11-27 22:49
pain, this is probably caused by a race condition where it calls regenerateplayer too soon, i'll look

**Comment by sapphonie** [comment] 2020-11-27 23:05
might be able to solve by calling `TF2_RemoveAllWeapons(client);` immediately before `TF2_RegeneratePlayer(client);`

**Comment by sapphonie** [comment] 2020-11-30 04:15
fixed in #3

**Closed as completed by sapphonie** 2020-11-30 04:15 UTC
